/**
 * The seed fleet. Photography is served from Unsplash's CDN (allow-listed in
 * next.config.ts); every URL below was verified to resolve before committing.
 */
export type SeedVehicle = {
  slug: string;
  name: string;
  brand: string;
  model: string;
  year: number;
  segment: "small" | "large" | "exclusive";
  bodyType: string;
  transmission: "Automatic" | "Manual";
  fuel: "Petrol" | "Diesel" | "Hybrid" | "Electric";
  seats: number;
  doors: number;
  bags: number;
  pricePerDay: number;
  costPerDay: number;
  photo: string;
  accentFrom: string;
  accentTo: string;
  rating: number;
  reviewCount: number;
  location: string;
  features: string[];
  description: string;
  unitsTotal: number;
  co2: number;
  /** relative demand weight — drives how many bookings the seeder assigns */
  demand: number;
};

const img = (id: string) => `https://images.unsplash.com/photo-${id}`;

export const SEED_FLEET: SeedVehicle[] = [
  {
    slug: "porsche-panamera-4s",
    name: "Porsche Panamera 4S",
    brand: "Porsche",
    model: "Panamera 4S",
    year: 2024,
    segment: "exclusive",
    bodyType: "Sedan",
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 4,
    doors: 4,
    bags: 3,
    pricePerDay: 289,
    costPerDay: 121,
    photo: img("1503376780353-7e6692767b70"),
    accentFrom: "#0f172a",
    accentTo: "#334155",
    rating: 4.9,
    reviewCount: 214,
    location: "London Heathrow",
    features: ["Adaptive cruise", "Bose audio", "Heated seats", "360° camera", "Sport Chrono"],
    description:
      "Executive grand tourer with the road manners of a sports car. The default choice for airport-to-boardroom runs where arriving unhurried matters.",
    unitsTotal: 4,
    co2: 205,
    demand: 7,
  },
  {
    slug: "ford-mustang-gt",
    name: "Ford Mustang GT",
    brand: "Ford",
    model: "Mustang GT",
    year: 2023,
    segment: "large",
    bodyType: "Coupe",
    transmission: "Manual",
    fuel: "Petrol",
    seats: 4,
    doors: 2,
    bags: 2,
    pricePerDay: 179,
    costPerDay: 74,
    photo: img("1494976388531-d1058494cdd8"),
    accentFrom: "#1f2937",
    accentTo: "#4b5563",
    rating: 4.8,
    reviewCount: 341,
    location: "Manchester City",
    features: ["5.0 V8", "Launch control", "Track apps", "Apple CarPlay"],
    description:
      "Five litres of naturally aspirated V8 and a six-speed manual. Booked most often for weekend coast runs and milestone birthdays.",
    unitsTotal: 5,
    co2: 270,
    demand: 10,
  },
  {
    slug: "chevrolet-camaro-rs",
    name: "Chevrolet Camaro RS",
    brand: "Chevrolet",
    model: "Camaro RS",
    year: 2023,
    segment: "large",
    bodyType: "Coupe",
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 4,
    doors: 2,
    bags: 2,
    pricePerDay: 165,
    costPerDay: 69,
    photo: img("1552519507-da3b142c6e3d"),
    accentFrom: "#0369a1",
    accentTo: "#0ea5e9",
    rating: 4.7,
    reviewCount: 188,
    location: "Birmingham Central",
    features: ["Heads-up display", "Dual-zone climate", "Wireless charging", "Bose audio"],
    description:
      "American muscle with a civil side. Comfortable enough for a long motorway leg, loud enough that nobody misses your arrival.",
    unitsTotal: 4,
    co2: 248,
    demand: 8,
  },
  {
    slug: "volkswagen-polo",
    name: "Volkswagen Polo",
    brand: "Volkswagen",
    model: "Polo Life",
    year: 2024,
    segment: "small",
    bodyType: "Hatchback",
    transmission: "Manual",
    fuel: "Petrol",
    seats: 5,
    doors: 5,
    bags: 2,
    pricePerDay: 46,
    costPerDay: 18,
    photo: img("1541899481282-d53bffe3c35d"),
    accentFrom: "#0e7490",
    accentTo: "#22d3ee",
    rating: 4.6,
    reviewCount: 512,
    location: "London Kings Cross",
    features: ["Lane assist", "Apple CarPlay", "Rear camera", "Cruise control"],
    description:
      "The sensible one. Cheap to fuel, easy to park, and small enough for the congestion zone without feeling like a penalty box.",
    unitsTotal: 12,
    co2: 118,
    demand: 14,
  },
  {
    slug: "ford-expedition",
    name: "Ford Expedition",
    brand: "Ford",
    model: "Expedition Limited",
    year: 2023,
    segment: "large",
    bodyType: "SUV",
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 7,
    doors: 5,
    bags: 5,
    pricePerDay: 142,
    costPerDay: 58,
    photo: img("1533473359331-0135ef1b58bf"),
    accentFrom: "#475569",
    accentTo: "#94a3b8",
    rating: 4.7,
    reviewCount: 267,
    location: "Edinburgh Airport",
    features: ["7 seats", "Tow package", "Panoramic roof", "Rear entertainment", "4WD"],
    description:
      "Seven proper seats and a boot that swallows a fortnight of luggage. Our most-booked vehicle for family holidays and film crews.",
    unitsTotal: 6,
    co2: 262,
    demand: 11,
  },
  {
    slug: "hyundai-i30-n",
    name: "Hyundai i30 N",
    brand: "Hyundai",
    model: "i30 N Performance",
    year: 2024,
    segment: "small",
    bodyType: "Hatchback",
    transmission: "Manual",
    fuel: "Petrol",
    seats: 5,
    doors: 5,
    bags: 2,
    pricePerDay: 78,
    costPerDay: 31,
    photo: img("1550355291-bbee04a92027"),
    accentFrom: "#b91c1c",
    accentTo: "#ef4444",
    rating: 4.8,
    reviewCount: 199,
    location: "Leeds City",
    features: ["Rev matching", "N mode", "Limited-slip diff", "Sport exhaust"],
    description:
      "A hot hatch that behaves in traffic and comes alive on a B-road. The enthusiast pick that still fits a family shop in the back.",
    unitsTotal: 5,
    co2: 168,
    demand: 9,
  },
  {
    slug: "mercedes-amg-gt",
    name: "Mercedes-AMG GT",
    brand: "Mercedes-Benz",
    model: "AMG GT",
    year: 2024,
    segment: "exclusive",
    bodyType: "Coupe",
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 2,
    doors: 2,
    bags: 1,
    pricePerDay: 349,
    costPerDay: 148,
    photo: img("1605559424843-9e4c228bf1c2"),
    accentFrom: "#b45309",
    accentTo: "#fbbf24",
    rating: 4.9,
    reviewCount: 126,
    location: "London Mayfair",
    features: ["AMG Ride Control", "Burmester audio", "Carbon trim", "Race mode"],
    description:
      "Long bonnet, short overhangs, and a soundtrack that makes tunnels a destination. Requires a 25+ licence held three years.",
    unitsTotal: 2,
    co2: 284,
    demand: 5,
  },
  {
    slug: "nissan-gt-r",
    name: "Nissan GT-R",
    brand: "Nissan",
    model: "GT-R Premium",
    year: 2023,
    segment: "exclusive",
    bodyType: "Coupe",
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 4,
    doors: 2,
    bags: 2,
    pricePerDay: 299,
    costPerDay: 126,
    photo: img("1568605117036-5fe5e7bab0b7"),
    accentFrom: "#1e3a8a",
    accentTo: "#3b82f6",
    rating: 4.8,
    reviewCount: 154,
    location: "Manchester City",
    features: ["AWD", "Launch control", "Bilstein DampTronic", "Titanium exhaust"],
    description:
      "All-wheel drive, twin-turbo, and physics-defying grip. Godzilla still makes supercar drivers check their mirrors.",
    unitsTotal: 2,
    co2: 275,
    demand: 6,
  },
  {
    slug: "bmw-m4-competition",
    name: "BMW M4 Competition",
    brand: "BMW",
    model: "M4 Competition",
    year: 2024,
    segment: "large",
    bodyType: "Coupe",
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 4,
    doors: 2,
    bags: 2,
    pricePerDay: 219,
    costPerDay: 92,
    photo: img("1502877338535-766e1452684a"),
    accentFrom: "#1d4ed8",
    accentTo: "#60a5fa",
    rating: 4.9,
    reviewCount: 298,
    location: "London Canary Wharf",
    features: ["M Drive", "Carbon bucket seats", "Adaptive M suspension", "Harman Kardon"],
    description:
      "The all-rounder of the performance fleet — genuinely usable daily, genuinely quick when you ask. Our highest repeat-booking rate.",
    unitsTotal: 4,
    co2: 234,
    demand: 12,
  },
  {
    slug: "fiat-500",
    name: "Fiat 500",
    brand: "Fiat",
    model: "500 Dolcevita",
    year: 2023,
    segment: "small",
    bodyType: "City car",
    transmission: "Manual",
    fuel: "Petrol",
    seats: 4,
    doors: 3,
    bags: 1,
    pricePerDay: 38,
    costPerDay: 14,
    photo: img("1549317661-bd32c8ce0db2"),
    accentFrom: "#0891b2",
    accentTo: "#67e8f9",
    rating: 4.5,
    reviewCount: 604,
    location: "Brighton Seafront",
    features: ["Fabric roof", "Bluetooth", "Eco mode", "City steering"],
    description:
      "The cheapest way to look good doing it. Fits in gaps other cars drive past and costs almost nothing to run.",
    unitsTotal: 14,
    co2: 109,
    demand: 15,
  },
  {
    slug: "bugatti-chiron",
    name: "Bugatti Chiron",
    brand: "Bugatti",
    model: "Chiron Pur Sport",
    year: 2023,
    segment: "exclusive",
    bodyType: "Hypercar",
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 2,
    doors: 2,
    bags: 1,
    pricePerDay: 2450,
    costPerDay: 980,
    photo: img("1580273916550-e323be2ae537"),
    accentFrom: "#334155",
    accentTo: "#cbd5e1",
    rating: 5,
    reviewCount: 41,
    location: "London Mayfair",
    features: ["W16 quad-turbo", "Chauffeur option", "Delivery included", "Dedicated handler"],
    description:
      "Chauffeur-only or advanced-driver assessed. Booked for launches, weddings and the occasional very good day.",
    unitsTotal: 1,
    co2: 516,
    demand: 2,
  },
  {
    slug: "toyota-rav4-hybrid",
    name: "Toyota RAV4 Hybrid",
    brand: "Toyota",
    model: "RAV4 Hybrid Excel",
    year: 2024,
    segment: "large",
    bodyType: "SUV",
    transmission: "Automatic",
    fuel: "Hybrid",
    seats: 5,
    doors: 5,
    bags: 4,
    pricePerDay: 89,
    costPerDay: 34,
    photo: img("1590362891991-f776e747a588"),
    accentFrom: "#166534",
    accentTo: "#4ade80",
    rating: 4.7,
    reviewCount: 433,
    location: "Bristol Temple",
    features: ["Hybrid AWD", "Adaptive cruise", "Wireless CarPlay", "Power tailgate"],
    description:
      "Does 50mpg without trying and has room for the dog. The pragmatic family booking that nobody regrets.",
    unitsTotal: 9,
    co2: 126,
    demand: 13,
  },
  {
    slug: "ferrari-laferrari",
    name: "Ferrari LaFerrari",
    brand: "Ferrari",
    model: "LaFerrari",
    year: 2022,
    segment: "exclusive",
    bodyType: "Hypercar",
    transmission: "Automatic",
    fuel: "Hybrid",
    seats: 2,
    doors: 2,
    bags: 0,
    pricePerDay: 3200,
    costPerDay: 1290,
    photo: img("1544636331-e26879cd4d9b"),
    accentFrom: "#7f1d1d",
    accentTo: "#ef4444",
    rating: 5,
    reviewCount: 23,
    location: "London Mayfair",
    features: ["HY-KERS hybrid", "Track delivery", "Dedicated handler", "Insurance included"],
    description:
      "Track-day delivery only, transported to and from the circuit. The halo car of the fleet and our highest-margin booking.",
    unitsTotal: 1,
    co2: 330,
    demand: 1,
  },
  {
    slug: "mercedes-amg-c63",
    name: "Mercedes-AMG C63",
    brand: "Mercedes-Benz",
    model: "AMG C63 S",
    year: 2023,
    segment: "large",
    bodyType: "Sedan",
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 5,
    doors: 4,
    bags: 3,
    pricePerDay: 198,
    costPerDay: 83,
    photo: img("1493238792000-8113da705763"),
    accentFrom: "#404040",
    accentTo: "#a3a3a3",
    rating: 4.8,
    reviewCount: 221,
    location: "Glasgow Central",
    features: ["AMG Performance seats", "Drift mode", "Burmester audio", "Head-up display"],
    description:
      "A four-door saloon that behaves like a sports car when provoked and a limousine when not. The corporate favourite.",
    unitsTotal: 4,
    co2: 251,
    demand: 9,
  },
];
