/**
 * The seed fleet — built around what Bangladeshi rental companies actually run.
 *
 * Reconditioned Japanese imports dominate the market, so the fleet is Toyota
 * heavy, the microbus is a first-class category rather than an afterthought,
 * and almost everything is offered with a driver. Photography is served from
 * Unsplash's CDN (allow-listed in next.config.ts); every URL below was checked
 * to resolve and visually confirmed to show the vehicle class it is named for.
 */
export type SeedVehicle = {
  slug: string;
  name: string;
  brand: string;
  model: string;
  year: number;
  /** small | large | exclusive — maps to the Small / Large / Exclusive Car tabs */
  segment: "small" | "large" | "exclusive";
  bodyType: string;
  transmission: "Automatic" | "Manual";
  fuel: "Petrol" | "Octane" | "Hybrid" | "Diesel";
  seats: number;
  doors: number;
  bags: number;
  /** Daily rate in BDT, with driver, inside Dhaka */
  pricePerDay: number;
  costPerDay: number;
  photo: string;
  accentFrom: string;
  accentTo: string;
  rating: number;
  reviewCount: number;
  location: string;
  features: string[];
  description: string;
  unitsTotal: number;
  co2: number;
  /** relative demand weight — drives how many bookings the seeder assigns */
  demand: number;
};

const img = (id: string) => `https://images.unsplash.com/photo-${id}`;

export const SEED_FLEET: SeedVehicle[] = [
  {
    slug: "suzuki-swift",
    name: "Suzuki Swift",
    brand: "Suzuki",
    model: "Swift GL",
    year: 2022,
    segment: "small",
    bodyType: "Hatchback",
    transmission: "Automatic",
    fuel: "Octane",
    seats: 5,
    doors: 5,
    bags: 2,
    pricePerDay: 3500,
    costPerDay: 1400,
    photo: img("1663852408695-f57f4d75a536"),
    accentFrom: "#0e7490",
    accentTo: "#22d3ee",
    rating: 4.5,
    reviewCount: 486,
    location: "Dhaka Dhanmondi",
    features: ["Air conditioning", "Bluetooth", "Reverse camera", "Driver included"],
    description:
      "The cheapest way to move around Dhaka without giving up air conditioning. Narrow enough for Dhanmondi side streets and light on fuel when the traffic will not move.",
    unitsTotal: 14,
    co2: 118,
    demand: 15,
  },
  {
    slug: "toyota-corolla",
    name: "Toyota Corolla",
    brand: "Toyota",
    model: "Corolla GLi",
    year: 2023,
    segment: "small",
    bodyType: "Sedan",
    transmission: "Automatic",
    fuel: "Octane",
    seats: 5,
    doors: 4,
    bags: 3,
    pricePerDay: 4000,
    costPerDay: 1600,
    photo: img("1638618164682-12b986ec2a75"),
    accentFrom: "#475569",
    accentTo: "#94a3b8",
    rating: 4.7,
    reviewCount: 612,
    location: "Dhaka Gulshan",
    features: ["Air conditioning", "Apple CarPlay", "Reverse camera", "Driver included", "Fuel card"],
    description:
      "The default booking. Everyone in Bangladesh has ridden in one, every mechanic can fix one, and it never causes a problem on a long Dhaka to Chattogram run.",
    unitsTotal: 18,
    co2: 132,
    demand: 18,
  },
  {
    slug: "toyota-corolla-axio-hybrid",
    name: "Toyota Corolla Axio Hybrid",
    brand: "Toyota",
    model: "Corolla Axio Hybrid",
    year: 2023,
    segment: "small",
    bodyType: "Sedan",
    transmission: "Automatic",
    fuel: "Hybrid",
    seats: 5,
    doors: 4,
    bags: 3,
    pricePerDay: 4500,
    costPerDay: 1750,
    photo: img("1626072557464-90403d788e8d"),
    accentFrom: "#166534",
    accentTo: "#4ade80",
    rating: 4.8,
    reviewCount: 398,
    location: "Dhaka Banani",
    features: ["Hybrid drivetrain", "Air conditioning", "Push start", "Driver included", "Fuel card"],
    description:
      "The hybrid Axio sips fuel in exactly the conditions Dhaka provides — stop, start, stop again. Our lowest running cost per kilometre and the corporate favourite.",
    unitsTotal: 12,
    co2: 94,
    demand: 16,
  },
  {
    slug: "toyota-premio",
    name: "Toyota Premio",
    brand: "Toyota",
    model: "Premio F",
    year: 2022,
    segment: "small",
    bodyType: "Sedan",
    transmission: "Automatic",
    fuel: "Octane",
    seats: 5,
    doors: 4,
    bags: 3,
    pricePerDay: 5500,
    costPerDay: 2150,
    photo: img("1623869675781-80aa31012a5a"),
    accentFrom: "#1e293b",
    accentTo: "#64748b",
    rating: 4.7,
    reviewCount: 341,
    location: "Dhaka Uttara",
    features: ["Leather seats", "Rear AC vents", "Push start", "Driver included", "Airport pickup"],
    description:
      "A step up from the Corolla in quietness and back-seat comfort. The car people book when a client or a relative is being collected from the airport.",
    unitsTotal: 10,
    co2: 141,
    demand: 13,
  },
  {
    slug: "honda-vezel",
    name: "Honda Vezel",
    brand: "Honda",
    model: "Vezel Z Hybrid",
    year: 2023,
    segment: "large",
    bodyType: "SUV",
    transmission: "Automatic",
    fuel: "Hybrid",
    seats: 5,
    doors: 5,
    bags: 4,
    pricePerDay: 6500,
    costPerDay: 2500,
    photo: img("1627395427294-d01af2f943ac"),
    accentFrom: "#b91c1c",
    accentTo: "#ef4444",
    rating: 4.8,
    reviewCount: 289,
    location: "Dhaka Gulshan",
    features: ["Hybrid drivetrain", "Panoramic roof", "Half leather", "Driver included", "Reverse camera"],
    description:
      "Ground clearance for a waterlogged monsoon street, hybrid economy for the commute, and a boot that takes a family's luggage. The most requested SUV on the fleet.",
    unitsTotal: 9,
    co2: 106,
    demand: 14,
  },
  {
    slug: "nissan-x-trail",
    name: "Nissan X-Trail",
    brand: "Nissan",
    model: "X-Trail 4WD",
    year: 2022,
    segment: "large",
    bodyType: "SUV",
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 7,
    doors: 5,
    bags: 4,
    pricePerDay: 7000,
    costPerDay: 2750,
    photo: img("1551817280-6d59c77ce1b8"),
    accentFrom: "#0f766e",
    accentTo: "#2dd4bf",
    rating: 4.6,
    reviewCount: 214,
    location: "Chattogram Agrabad",
    features: ["4WD", "7 seats", "Roof rails", "Driver included", "Long-trip ready"],
    description:
      "Seven seats and four-wheel drive for the hill tracts. Booked most often for Bandarban and Rangamati trips where the road stops being a road.",
    unitsTotal: 6,
    co2: 168,
    demand: 10,
  },
  {
    slug: "toyota-hiace-microbus",
    name: "Toyota Hiace Microbus",
    brand: "Toyota",
    model: "Hiace Premia",
    year: 2023,
    segment: "large",
    bodyType: "Microbus",
    transmission: "Manual",
    fuel: "Diesel",
    seats: 11,
    doors: 4,
    bags: 8,
    pricePerDay: 8000,
    costPerDay: 3100,
    photo: img("1650807486050-a142ea418b19"),
    accentFrom: "#334155",
    accentTo: "#cbd5e1",
    rating: 4.7,
    reviewCount: 527,
    location: "Dhaka Motijheel",
    features: ["11 seats", "Roof AC", "Luggage rack", "Driver included", "Intercity permit"],
    description:
      "The workhorse of Bangladeshi travel. Eleven seats, a roof air conditioner that actually copes, and enough luggage space for a wedding party or an office picnic.",
    unitsTotal: 11,
    co2: 210,
    demand: 17,
  },
  {
    slug: "mitsubishi-pajero-sport",
    name: "Mitsubishi Pajero Sport",
    brand: "Mitsubishi",
    model: "Pajero Sport GLS",
    year: 2022,
    segment: "large",
    bodyType: "SUV",
    transmission: "Automatic",
    fuel: "Diesel",
    seats: 7,
    doors: 5,
    bags: 5,
    pricePerDay: 12000,
    costPerDay: 4700,
    photo: img("1594978100646-ccd2ae32b711"),
    accentFrom: "#1f2937",
    accentTo: "#4b5563",
    rating: 4.7,
    reviewCount: 186,
    location: "Dhaka Banani",
    features: ["4WD", "7 seats", "High clearance", "Driver included", "Intercity permit"],
    description:
      "Diesel, high off the ground, and unbothered by a flooded underpass. The standard choice for NGO field visits and anything that leaves the highway.",
    unitsTotal: 5,
    co2: 224,
    demand: 8,
  },
  {
    slug: "mercedes-benz-c-class",
    name: "Mercedes-Benz C-Class",
    brand: "Mercedes-Benz",
    model: "C 200",
    year: 2022,
    segment: "exclusive",
    bodyType: "Sedan",
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 5,
    doors: 4,
    bags: 3,
    pricePerDay: 18000,
    costPerDay: 7100,
    photo: img("1551836989-b4622a17a792"),
    accentFrom: "#404040",
    accentTo: "#a3a3a3",
    rating: 4.8,
    reviewCount: 96,
    location: "Dhaka Gulshan",
    features: ["Uniformed chauffeur", "Leather interior", "Burmester audio", "Bottled water", "Airport pickup"],
    description:
      "Discreet rather than loud. Booked for board meetings, visiting delegations and the kind of arrival where the car should not be the story.",
    unitsTotal: 3,
    co2: 178,
    demand: 6,
  },
  {
    slug: "toyota-land-cruiser-prado",
    name: "Toyota Land Cruiser Prado",
    brand: "Toyota",
    model: "Land Cruiser Prado TX",
    year: 2023,
    segment: "exclusive",
    bodyType: "SUV",
    transmission: "Automatic",
    fuel: "Diesel",
    seats: 7,
    doors: 5,
    bags: 6,
    pricePerDay: 20000,
    costPerDay: 7900,
    photo: img("1630826362226-a509049bcdbf"),
    accentFrom: "#3f3f46",
    accentTo: "#a1a1aa",
    rating: 4.9,
    reviewCount: 118,
    location: "Hazrat Shahjalal Airport",
    features: ["4WD", "7 seats", "Uniformed chauffeur", "Intercity permit", "Airport pickup"],
    description:
      "The car that goes anywhere in Bangladesh and looks right doing it. Standard issue for embassy movements, senior management and long upcountry programmes.",
    unitsTotal: 4,
    co2: 235,
    demand: 7,
  },
  {
    slug: "mercedes-benz-e-class",
    name: "Mercedes-Benz E-Class",
    brand: "Mercedes-Benz",
    model: "E 200 Avantgarde",
    year: 2023,
    segment: "exclusive",
    bodyType: "Sedan",
    transmission: "Automatic",
    fuel: "Petrol",
    seats: 5,
    doors: 4,
    bags: 3,
    pricePerDay: 25000,
    costPerDay: 9800,
    photo: img("1624085568108-36410cfe4d24"),
    accentFrom: "#111827",
    accentTo: "#6b7280",
    rating: 4.9,
    reviewCount: 74,
    location: "Dhaka Gulshan",
    features: ["Uniformed chauffeur", "Decoration allowed", "Ambient lighting", "Bottled water", "Full-day minimum"],
    description:
      "Our most-booked wedding car. Comes cleaned, fuelled and with a chauffeur in uniform; floral decoration is permitted and fitted by our team on the morning.",
    unitsTotal: 3,
    co2: 165,
    demand: 5,
  },
  {
    slug: "toyota-land-cruiser-v8",
    name: "Toyota Land Cruiser V8",
    brand: "Toyota",
    model: "Land Cruiser 200 V8",
    year: 2022,
    segment: "exclusive",
    bodyType: "SUV",
    transmission: "Automatic",
    fuel: "Diesel",
    seats: 7,
    doors: 5,
    bags: 7,
    pricePerDay: 35000,
    costPerDay: 13800,
    photo: img("1610064094665-57e727e29f8b"),
    accentFrom: "#0f172a",
    accentTo: "#475569",
    rating: 5,
    reviewCount: 41,
    location: "Dhaka Gulshan",
    features: ["4WD", "Uniformed chauffeur", "Tinted glass", "Escort friendly", "Full-day minimum"],
    description:
      "The VIP movement car. Diplomatic missions and visiting executives book it by the week; it is the only vehicle we release with a named, vetted chauffeur.",
    unitsTotal: 2,
    co2: 268,
    demand: 3,
  },
];
