/**
 * Build-time pipeline: turns a 108KB TopoJSON world atlas into a small set of
 * pre-projected SVG paths so the browser never has to download topojson/d3-geo.
 *
 * Run with: npm run build:map
 */
import { readFileSync, writeFileSync } from "node:fs";
import { geoNaturalEarth1, geoPath } from "d3-geo";
import { feature } from "topojson-client";

const WIDTH = 900;
const HEIGHT = 460;

const topology = JSON.parse(readFileSync("scripts/countries-110m.json", "utf8"));
const collection = feature(topology, topology.objects.countries) as unknown as {
  features: Array<{ id: string; properties: { name: string }; geometry: unknown }>;
};

const projection = geoNaturalEarth1().fitSize([WIDTH, HEIGHT], collection as never);
const path = geoPath(projection);

// Round coordinates to 1dp — invisible at this scale, ~40% smaller payload.
const round = (d: string) => d.replace(/-?\d+\.\d+/g, (n) => String(Math.round(Number(n) * 10) / 10));

const shapes = collection.features
  .map((f) => ({ id: f.id, name: f.properties.name, d: round(path(f as never) ?? "") }))
  // A handful of atlas entries (disputed / unrecognised territories) carry no ISO id.
  .filter((s): s is { id: string; name: string; d: string } => Boolean(s.d) && Boolean(s.id))
  // Antarctica adds a lot of path data and nothing to the story.
  .filter((s) => s.name !== "Antarctica");

const out = `// AUTO-GENERATED by scripts/build-world-map.mts — do not edit by hand.
// Source: world-atlas@2 countries-110m, projected with d3-geo geoNaturalEarth1.

export const WORLD_VIEWBOX = "0 0 ${WIDTH} ${HEIGHT}";

export type CountryShape = { id: string; name: string; d: string };

export const WORLD_SHAPES: CountryShape[] = ${JSON.stringify(shapes)};
`;

writeFileSync("src/components/charts/world-shapes.ts", out);
console.log(`Wrote ${shapes.length} country shapes (${(out.length / 1024).toFixed(0)}KB).`);
